### ISSUE TITLE
[JENKINS-57288] NoClassDefFoundError on SingleConditionalBuilder

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/conditional-buildstep-plugin#204]
<p>After upgrading Jenkins from 2.89.3 to 2.164.2 and then upgrading the Conditional Build step plugin to 1.3.6, we started seeing the following error whenever a Jenkins job is triggered using "Poll SCM".</p>

<p>FATAL: org/jenkinsci/plugins/conditionalbuildstep/singlestep/SingleConditionalBuilder<br/>
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/conditionalbuildstep/singlestep/SingleConditionalBuilder<br/>
 at com.microfocus.application.automation.tools.octane.model.processors.projects.AbstractProjectProcessor.builderClassValidator(AbstractProjectProcessor.java:189)<br/>
 at com.microfocus.application.automation.tools.octane.model.processors.projects.AbstractProjectProcessor.processBuilders(AbstractProjectProcessor.java:145)<br/>
 at com.microfocus.application.automation.tools.octane.model.processors.projects.AbstractProjectProcessor.processBuilders(AbstractProjectProcessor.java:131)<br/>
 at com.microfocus.application.automation.tools.octane.model.processors.projects.FreeStyleProjectProcessor.<init>(FreeStyleProjectProcessor.java:40)<br/>
 at com.microfocus.application.automation.tools.octane.model.processors.projects.JobProcessorFactory.getFlowProcessor(JobProcessorFactory.java:68)<br/>
 at com.microfocus.application.automation.tools.octane.model.processors.projects.JobProcessorFactory.getFlowProcessor(JobProcessorFactory.java:60)<br/>
 at com.microfocus.application.automation.tools.octane.tests.build.BuildHandlerUtils.getJobCiId(BuildHandlerUtils.java:138)<br/>
 at com.microfocus.application.automation.tools.octane.model.CIEventFactory.createScmEvent(CIEventFactory.java:70)<br/>
 at com.microfocus.application.automation.tools.octane.events.SCMListenerOctaneImpl.onChangeLogParsed(SCMListenerOctaneImpl.java:44)<br/>
 at hudson.model.listeners.SCMListener.onChangeLogParsed(SCMListener.java:120)<br/>
 at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:590)<br/>
 at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)<br/>
 at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)<br/>
 at hudson.model.Run.execute(Run.java:1816)<br/>
 at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)<br/>
 at hudson.model.ResourceController.execute(ResourceController.java:97)<br/>
 at hudson.model.Executor.run(Executor.java:429)</p>

<p> </p>

<p>I then downgraded the Conditional Build Step plugin to 1.3.5, but we are still seeing this error.  </p>

<p>If we run the job manually it succeeds.</p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=calvinmichel">calvinmichel</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-57288" target="_blank">NoClassDefFoundError on SingleConditionalBuilder</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/domi.png" title="domi's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=domi">domi</a>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: conditional-buildstep-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20260107-133739
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After upgrading Jenkins from 2.89.3 to 2.164.2 and then upgrading the Conditional Build step plugin to 1.3.6, we started seeing the following error whenever a Jenkins job is triggered using "Poll SCM".</p>

<p>FATAL: org/jenkinsci/plugins/conditionalbuildstep/singlestep/SingleConditionalBuilder
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/conditionalbuildstep/singlestep/SingleConditionalBuilder
 at com.microfocus.application.automation.tools.octane.model.processors.projects.AbstractProjectProcessor.builderClassValidator(AbstractProjectProcessor.java:189)
 at com.microfocus.application.automation.tools.octane.model.processors.projects.AbstractProjectProcessor.processBuilders(AbstractProjectProcessor.java:145)
 at com.microfocus.application.automation.tools.octane.model.processors.projects.AbstractProjectProcessor.processBuilders(AbstractProjectProcessor.java:131)
 at com.microfocus.application.automation.tools.octane.model.processors.projects.FreeStyleProjectProcessor.&lt;init&gt;(FreeStyleProjectProcessor.java:40)
 at com.microfocus.application.automation.tools.octane.model.processors.projects.JobProcessorFactory.getFlowProcessor(JobProcessorFactory.java:68)
 at com.microfocus.application.automation.tools.octane.model.processors.projects.JobProcessorFactory.getFlowProcessor(JobProcessorFactory.java:60)
 at com.microfocus.application.automation.tools.octane.tests.build.BuildHandlerUtils.getJobCiId(BuildHandlerUtils.java:138)
 at com.microfocus.application.automation.tools.octane.model.CIEventFactory.createScmEvent(CIEventFactory.java:70)
 at com.microfocus.application.automation.tools.octane.events.SCMListenerOctaneImpl.onChangeLogParsed(SCMListenerOctaneImpl.java:44)
 at hudson.model.listeners.SCMListener.onChangeLogParsed(SCMListener.java:120)
 at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:590)
 at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
 at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
 at hudson.model.Run.execute(Run.java:1816)
 at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
 at hudson.model.ResourceController.execute(ResourceController.java:97)
 at hudson.model.Executor.run(Executor.java:429)</p>

<p> </p>

<p>I then downgraded the Conditional Build Step plugin to 1.3.5, but we are still seeing this error.  </p>

<p>If we run the job manually it succeeds.</p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins 2.164.2<br/>
Conditional Build Step 1.3.5<br/>
Token Macro 2.3<br/>
```
</details>
